
<ivy-module version="2.0">
	<info organisation="kairosd.org" module="kairosdb"/>
	<configurations defaultconf="default" >
		<conf name="default"/>
		<conf name="integration" extends="test"/>
		<conf name="test" extends="default"/>
		<conf name="build_tools"/>
	</configurations>
	<dependencies>
		<dependency org="com.google.guava" name="guava" rev="32.1.3-jre" force="true">
			<artifact name="guava" type="bundle" ext="jar"/>
		</dependency>

		<dependency org="com.github.rholder" name="guava-retrying" rev="2.0.0" />
		<dependency org="org.apache.commons" name="commons-lang3" rev="3.19.0" />
		<dependency org="org.apache.commons" name="commons-collections4" rev="4.1" />

		<dependency org="org.json" name="json" rev="20250517" />
		<dependency org="com.google.code.gson" name="gson" rev="2.8.9" />
		<dependency org="junit" name="junit" rev="4.13.2" conf="test->default" />

		<dependency org="org.hamcrest" name="hamcrest-library" rev="1.3"
		            conf="test->default"/>

		<dependency org="org.mockito" name="mockito-core" rev="2.23.0" conf="test->default"/>
		<dependency org="org.assertj" name="assertj-core" rev="3.14.0"
					conf="test->default"/>
		<dependency org="org.assertj" name="assertj-guava" rev="3.3.0"
		            conf="test->default"/>

		<dependency org="io.netty" name="netty-all" rev="4.1.128.Final" />

		<dependency org="com.google.inject" name="guice" rev="${guice.version}" />
		<dependency org="com.google.inject.extensions" name="guice-assistedinject" rev="${guice.version}" />
		<dependency org="com.google.inject.extensions" name="guice-servlet" rev="${guice.version}" />
		<dependency org="com.h2database" name="h2" rev="2.4.240" />
		<dependency org="org.kairosdb" name="bigqueue" rev="1.0.4" />

		<!-- OTLP support -->
		<dependency org="io.grpc" name="grpc-netty-shaded" rev="1.76.0"/>
		<dependency org="io.grpc" name="grpc-protobuf" rev="1.76.0"/>
		<dependency org="io.grpc" name="grpc-stub" rev="1.76.0"/>
		<dependency org="io.opentelemetry.proto" name="opentelemetry-proto" rev="1.8.0-alpha"/>

		<dependency org="com.typesafe" name="config" rev="1.4.0" />

		<dependency org="org.xerial.snappy" name="snappy-java" rev="1.1.10.8"/>

		<dependency org="org.projectlombok" name="lombok" rev="1.18.22" />

		<!-- provides connection pooling -->
		<dependency org="com.mchange" name="c3p0" rev="0.9.5.5"/>
		<dependency org="org.apache.commons" name="commons-math3" rev="3.2" />
		<dependency org="commons-io" name="commons-io" rev="2.21.0" />
		<dependency org="com.beust" name="jcommander" rev="1.75" />
		<dependency org="org.apache.httpcomponents" name="httpclient" rev="4.5.14" />
		<dependency org="commons-codec" name="commons-codec" rev="1.19.0"/> <!-- force dependency update for httpclient -->
		<dependency org="joda-time" name="joda-time" rev="2.10.6" />

		<!-- Logging dependencies -->
		<dependency org="ch.qos.logback" name="logback-core" rev="1.5.21" />
		<dependency org="ch.qos.logback" name="logback-classic" rev="1.5.21" />
		<dependency org="org.slf4j" name="slf4j-api" rev="2.0.17" />
		<dependency org="org.slf4j" name="jul-to-slf4j" rev="2.0.17" />

		<!--Genormous dependencies-->
		<dependency org="org.agileclick.genorm" name="genormous" rev="1.6.5.jdbc41" conf="default,build_tools->default">
			<exclude org="javax.servlet" name="servlet-api"/>
			<exclude org="org.agileclick.slickxml" name="slickxml"/>
			<exclude org="org.agileclick.ultramc" name="ultramc"/>
			<exclude org="dom4j" name="dom4j"/>
			<exclude org="org.antlr" name="stringtemplate"/>
			<exclude org="jaxen" name="jaxen"/>
		</dependency>
		<dependency org="dom4j" name="dom4j" rev="1.6.1" conf="build_tools->default"/>
		<dependency org="org.antlr" name="stringtemplate" rev="3.2.1" conf="build_tools->default"/>
		<dependency org="jaxen" name="jaxen" rev="1.1.6" transitive="false" conf="build_tools->default">
			<artifact name="jaxen" type="jar"/>
		</dependency>

		<!-- Cassandra Client -->
		<dependency org="org.apache.cassandra" name="cassandra-driver-core" rev="3.12.1">
			<exclude org="com.fasterxml.jackson.core" name="jackson-databind"/>
		</dependency>
		<dependency org="net.jpountz.lz4" name="lz4" rev="1.3.0"/>


		<!-- Jetty server stuff -->
		<dependency org="org.eclipse.jetty" name="jetty-server"
		            rev="${jetty.version}"/>
		<dependency org="org.eclipse.jetty.ee10" name="jetty-ee10-servlet"
		            rev="${jetty.version}"/>
		<dependency org="org.eclipse.jetty.ee10" name="jetty-ee10-servlets"
		            rev="${jetty.version}"/>
		<!--<dependency org="org.eclipse.jetty" name="jetty-jaas"
		            rev="${jetty.version}"/>-->
		<dependency org="org.apache.mina" name="mina-core" rev="2.2.4"/> <!-- force dependency update for jetty-jaas -->

		<!--Jersey-->
		<!-- <dependency org="org.glassfish.jersey.containers" name="jersey-container-servlet" rev="${jersey.version}"/>
		<dependency org="org.glassfish.jersey.inject" name="jersey-hk2" rev="${jersey.version}"/>
		<dependency org="org.glassfish.jersey.ext" name="jersey-bean-validation" rev="${jersey.version}"/>
		<dependency org="org.glassfish.jersey.media" name="jersey-media-json-jackson" rev="${jersey.version}"/>
		<dependency org="org.glassfish.jersey.security" name="oauth1-server" rev="${jersey.version}"/>
		<dependency org="org.glassfish.jersey.security" name="oauth1-signature" rev="${jersey.version}"/>
		<dependency org="org.glassfish.hk2" name="guice-bridge" rev="3.1.1"/> -->


		<dependency org="org.jboss.resteasy" name="resteasy-servlet-initializer" rev="${resteasy.version}"/>
		<dependency org="org.jboss.resteasy" name="resteasy-core" rev="${resteasy.version}"/>
		<dependency org="org.jboss.resteasy" name="resteasy-jackson2-provider" rev="${resteasy.version}"/>

		<dependency org="jakarta.el" name="jakarta.el-api" rev="5.0.1"/>
		<dependency org="org.glassfish" name="jakarta.el" rev="5.0.0-M1"/>

		<dependency org="jakarta.ws.rs" name="jakarta.ws.rs-api" rev="3.1.0"/>
		<dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.20.1"/>
		<dependency org="com.fasterxml.jackson.jakarta.rs" name="jackson-jakarta-rs-json-provider" rev="2.20.1"/>





		<!-- <dependency org="com.sun.jersey.contribs" name="jersey-guice"
		            rev="${jersey.version}"/>
		<dependency org="com.sun.jersey" name="jersey-server" rev="${jersey.version}"/>
		<dependency org="com.sun.jersey" name="jersey-core" rev="${jersey.version}"/>
		<dependency org="com.sun.jersey" name="jersey-servlet" rev="${jersey.version}"
		            transitive="false"/>
		<dependency org="com.sun.jersey.contribs.jersey-oauth" name="oauth-signature" rev="${jersey.version}" />
		<dependency org="com.sun.jersey.contribs.jersey-oauth" name="oauth-server" rev="${jersey.version}" />
		<dependency org="com.fasterxml.jackson.jaxrs" name="jackson-jaxrs-json-provider" rev="2.20.1"/>-->


		<!-- Pulse -->
		<dependency org="jakarta.validation" name="jakarta.validation-api" rev="3.1.0"/>
		<dependency org="org.hibernate.validator" name="hibernate-validator" rev="8.0.3.Final"/>
		<dependency org="com.google.code.findbugs" name="jsr305" rev="1.3.9"/>

		<!-- Quartz -->
		<dependency org="org.quartz-scheduler" name="quartz" rev="2.3.2" />

		<!-- Codehale Metrics -->
		<dependency org="io.dropwizard.metrics" name="metrics-healthchecks"
		            rev="3.2.6"/>
		<dependency org="io.dropwizard.metrics" name="metrics-jvm" rev="3.2.6"/>

		<dependency org="org.testng" name="testng" rev="7.11.0" conf="integration->default"/>

		<dependency org="org.kairosdb" name="metrics4j" rev="1.0.4"/>

		<!-- Dependencies removed in jdk9 -->
		<dependency org="jakarta.xml.bind" name="jakarta.xml.bind-api" rev="4.0.2" />
		<dependency org="org.glassfish.jaxb" name="jaxb-runtime" rev="4.0.5" />
		<dependency org="jakarta.activation" name="jakarta.activation-api" rev="2.1.3" />

		<dependency org="jakarta.servlet" name="jakarta.servlet-api" rev="6.1.0" />



		<!-- Build tools -->
		<dependency org="org.gaul" name="modernizer-maven-plugin" rev="2.0.0" conf="build_tools->default" />

		<!-- Must match dependency declared above -->
		<conflict org="com.google.guava" module="guava" rev="32.1.3-jre"/>

	</dependencies>
</ivy-module>
