package org.kairosdb.core.processingstage;

import com.google.common.collect.ImmutableList;
import org.kairosdb.core.processingstage.metadata.QueryProcessingStageMetadata;

public interface QueryProcessingChain
{

    /**
     * Returns an {@link ImmutableList} of {@link QueryProcessingStageFactory}
     * instance contained into the processing chain.
     *
     * @return the {@link ImmutableList} describing the processing chain
     */
    ImmutableList<QueryProcessingStageFactory<?>> getQueryProcessingStageFactories();

    /**
     * Returns an {@link QueryProcessingStageFactory} instance whose can generate
     * query processors.
     * The query processor type must be precised in parameters.
     *
     * @param queryProcessorFamily  query processor type generated by the
     *                              {@link QueryProcessingStageFactory}
     * @return                      instance of {@link QueryProcessingStageFactory}
     */
    QueryProcessingStageFactory<?> getQueryProcessingStageFactory(Class<?> queryProcessorFamily);

    /**
     * Returns an {@link QueryProcessingStageFactory} instance whose can generate
     * query processors.
     * The {@link QueryProcessingStageFactory} name must be precised in parameters.
     *
     * @param queryProcessorFamilyName  name of the {@link QueryProcessingStageFactory}
     * @return                          instance of {@link QueryProcessingStageFactory}
     */
    QueryProcessingStageFactory<?> getQueryProcessingStageFactory(String queryProcessorFamilyName);

    /**
     * Returns an {@link ImmutableList} of {@link QueryProcessingStageMetadata}
     * describing the processing chain.
     *
     * @return the {@link ImmutableList} describing the processing chain
     */
    ImmutableList<QueryProcessingStageMetadata> getQueryProcessingChainMetadata();
}
