package org.kairosdb.datastore.h2.orm;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
	Counts the data points for a metric query.
*/
public class CountDataPointsForMetricData extends CountDataPointsForMetricQuery.Record
	{
	public CountDataPointsForMetricData(CountDataPointsForMetricQuery query, java.sql.ResultSet resultSet)
			throws java.sql.SQLException
		{
		query.super(resultSet);
		}
	}