package org.kairosdb.datastore.h2.orm;

/**
 * This class has been automatically generated by GenORMous.  This file is for
 * adding custom code to.  This file will not be regenerated once it exists.
 */
public class ServiceIndex extends ServiceIndex_base
{
}