package net.opentsdb.datastore.h2.orm;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
*/
public class TagNamesData extends TagNamesQuery.Record
	{
	public TagNamesData(TagNamesQuery query, java.sql.ResultSet resultSet)
			throws java.sql.SQLException
		{
		query.super(resultSet);
		}
	}