package net.opentsdb.datastore.h2.orm;

/**
	This class has been automatically generated by GenORMous.  This file is for
	adding custom code to.  This file will not be regenerated once it exists.
	
	Returns the super set of tags that are in a datapoint set
*/
public class TagsInQueryData extends TagsInQueryQuery.Record
	{
	public TagsInQueryData(TagsInQueryQuery query, java.sql.ResultSet resultSet)
			throws java.sql.SQLException
		{
		query.super(resultSet);
		}
	}