enabled: true

image:
  repository: kairosdb # this must be changed when we onboard kairosdb to official dockerhub repository.
  tag: 1.3.2-1
  pullPolicy: Always


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:


config:
  # This configuration will override what is in kairosdb.conf.  The layout is the same.
  # The only restriction is you cannot combine levels together like you can in
  # hocon, you cannot do service.telnet:  That will be seen as one level instead
  # of two.
  kairosdb:
    metric-prefix: "mykairos."

    service:
      #Change this value to "<disabled>" to disable telnet server
      telnet: "org.kairosdb.core.telnet.TelnetServerModule"

      #datastore: "org.kairosdb.datastore.h2.H2Module"
      datastore: "org.kairosdb.datastore.cassandra.CassandraModule"

    telnetserver:
      port: 4242
      address: "0.0.0.0"

    datastore:
      cassandra:
        write_cluster:
          replication: "{'class': 'SimpleStrategy','replication_factor' : 1}"
          cql_host_list:
          - "localhost"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      http:
        paths:
            - path: /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 1
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
